# Permalinks
permalink:           pretty

# Setup
title:               Hello World
tagline:             'code life'
description:         'nothing'
url:                 https://nishisbma.com
baseurl:             ''
paginate:            5
excerpt_separator:   '<!-- more -->'
analytics_id:        'UA-77732769-1'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed
  
# About/contact
author:
  name:              Zeng Jie
  url:               https://twitter.com/zjengjie
  email:             zjengjie@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
