# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Hello World
tagline:             'code life'
description:         ''
url:                 http://zjengjie.github.io
baseurl:             ''
paginate:            5
excerpt_separator:   '<!-- more -->'
highlighter:         pygments

# About/contact
author:
  name:              Zeng Jie
  url:               https://twitter.com/zjengjie
  email:             zjengjie@gmail.com

gems: [jekyll-paginate]

# Custom vars
version:             1.0.0

